### ISSUE TITLE
Error while setting up tibber_data platform for sensor

### ISSUE THREAD

**Issue by monsivar** [Danielhiversen/home_assistant_tibber_data#21]
Logger: homeassistant.components.sensor
Source: custom_components/tibber_data/sensor.py:52
Integration: sensor (documentation, issues)
First occurred: 09:00:26 (1 occurrences)
Last logged: 09:00:26

Error while setting up tibber_data platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tibber_data/sensor.py", line 52, in async_setup_platform
    for (
TypeError: 'NoneType' object is not iterable

**Comment by Danielhiversen** [comment]
Fixed by https://github.com/Danielhiversen/home_assistant_tibber_data/commit/98b1a97c96a579671a7cf8634dc3e817b1274a41
